### ISSUE TITLE
We should not require the reference field

### ISSUE THREAD

**Issue by kyleniemeyer** [pr-omethe-us/PyKED#76] opened 2017-09-26 19:43 UTC
As pointed out by a reviewer for our IJCK submission, we want people to use the ChemKED format internally and submit alongside articles. This is impossible right now, because we require a reference.

I propose that we remove `reference` from the required list of fields. It should still be required when submitting something to our database, though.

**Comment by bryanwweber** [comment] 2017-09-26 20:34
Would it be better to allow disabling the reference checker specifically, and leave it on by default?

**Comment by kyleniemeyer** [comment] 2017-09-26 20:41
Hmm... I guess I'm not sure. Either way I do think it should be an option the way fully disabling validation is now.

**Comment by bryanwweber** [comment] 2017-09-26 20:57
Yes, I think the recommendation for now would be to turn off all the validation.

So, I think we should break the validation into related chunks that can be turned on or off as desired. As part of that, the reference checking can be turned off. The question then is whether it should be on or off by default. I think I would prefer on by default, but its not a strong preference.

I think this is actually a duplicate of #39 then.

**Comment by kyleniemeyer** [comment] 2017-09-26 22:47
OK, I think it is. We can continue the conversation there.

**Comment by bryanwweber** [comment] 2017-10-01 14:04
I'm going to reopen this because I think it merits a bit more discussion.

So I looked at the schema, and I thought the only required fields were year and authors, but it turns out journal is also required. So I propose leaving the `reference` as required, but only requiring the `year` and `authors` subfields. This way, people can include a very basic `reference` if they want to use the files internally before publication, but it also helps them stay organized a little bit. Thoughts?

**Comment by kyleniemeyer** [comment] 2017-10-02 14:55
OK, this seems fine. It seems reasonable to keep `authors` and `year`.

**Closed** 2017-10-02 21:23 UTC
